actor_beta: 1.0
actor_learning_rate: 0.001
alpha_learning_rate: 0.001
batch_size: 1024
critic_beta: 1.0
critic_layernorm: true
critic_learning_rate: 0.001
dataset_name: "walker2d-random-v2"
eval_episodes: 10
eval_every: 50
eval_seed: 42
gamma: 0.99
group: "sac-rnd-walker2d-random-v2-multiseed-v0"
hidden_dim: 256
name: "SAC-RND"
normalize_reward: false
num_critics: 2
num_epochs: 3000
num_updates_on_epoch: 1000
project: "CORL"
rnd_embedding_dim: 32
rnd_hidden_dim: 256
rnd_learning_rate: 0.0003
rnd_num_epochs: 1
tau: 0.005
train_seed: 10
