batch_size: 256
buffer_size: 10000000
checkpoints_path: null
device: cuda
discount: 0.99
env: antmaze-medium-play-v0
eval_freq: 5000
frac: 1.0
group: bc-antmaze-medium-play-v0-multiseed-v0
load_model: ''
max_timesteps: 1000000
max_traj_len: 1000
n_episodes: 100
name: BC
normalize: true
project: CORL
seed: 0
