awac_lambda: 0.1
batch_size: 256
buffer_size: 10000000
checkpoints_path: null
deterministic_torch: true
device: cuda
env_name: maze2d-umaze-dense-v1
eval_frequency: 1000
gamma: 0.99
group: awac-maze2d-umaze-dense-v1-multiseed-v0
hidden_dim: 256
learning_rate: 0.0003
n_test_episodes: 100
num_train_ops: 1000000
project: CORL
seed: 42
tau: 0.005
test_seed: 69
