actor_beta: 0.5
actor_learning_rate: 0.0003
alpha_learning_rate: 0.0003
batch_size: 256
critic_beta: 0.01
critic_layernorm: true
critic_learning_rate: 0.0003
dataset_name: "antmaze-large-diverse-v1"
eval_episodes: 10
eval_every: 50
eval_seed: 42
gamma: 0.999
group: "sac-rnd-antmaze-large-diverse-v1-multiseed-v0"
hidden_dim: 256
name: "SAC-RND"
normalize_reward: true
num_critics: 2
num_epochs: 3000
num_updates_on_epoch: 1000
project: "CORL"
rnd_embedding_dim: 32
rnd_hidden_dim: 256
rnd_learning_rate: 0.0003
rnd_num_epochs: 1
tau: 0.005
train_seed: 10
