batch_size: 256
buffer_size: 1000000
checkpoints_path: null
dataset_id: hammer-cloned-v1
eval_episodes: 10
eval_every: 5000
eval_seed: 0
gamma: 1.0
group: bc-10-hammer-cloned-v1-multiseed-v0
name: bc-10
normalize_state: true
project: CORL
top_fraction: 0.1
train_seed: 0
update_steps: 1000000